Task 1

List creation and manipulation

In [1]:
lst=[1,2,3]
print(lst)
lst.append(4)
print(lst)

[1, 2, 3]
[1, 2, 3, 4]


Tuple creation and manipulation

In [2]:
tup=(1,3,5)
print(tup)

(1, 3, 5)


Set creation and manipulation

In [3]:
set={2,4,6}
print(set)

{2, 4, 6}


Dictionary creation and manipulation

In [4]:
dict={'a':1,'b':2}
print(dict)
dict['c']=3
print(dict)

{'a': 1, 'b': 2}
{'a': 1, 'b': 2, 'c': 3}


Task 2

Numpy arrays and statistics

In [5]:
import numpy as np

In [6]:
num=np.array([n for n in range(1,11)])
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
mean=np.mean(num)
min=np.min(num)
max=np.max(num)
print("Mean:",mean,"\nMin",min,"\nMax",max)

Mean: 5.5 
Min 1 
Max 10


Task 3

Pandas CSV load

In [8]:
import pandas as pd

In [9]:
df=pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB


Task 4

Dynamic Data Structure

In [11]:
dict1={}
for i in range(3):
    key=input("Enter a key:")
    value=int(input("Enter the value:"))
    dict1[key]=value
print(dict1)

{'x': 1, 'y': 2, 'z': 3}


Task 5

NumPy Matrix Operations

In [12]:
num1=np.array([[1,2],[3,4]])
num2=np.array([[5,6],[7,8]])
sum=num1+num2
print(sum)

[[ 6  8]
 [10 12]]


In [13]:
dot=num1.dot(num2)
dot

array([[19, 22],
       [43, 50]])

In [14]:
prod=num1*num2
prod

array([[ 5, 12],
       [21, 32]])

In [ ]:
mat_prod=num1@num2
mat_prod

array([[19, 22],
       [43, 50]])

: 